### ISSUE TITLE
Add date to time

### ISSUE THREAD

**Issue by xJoe** [mddub/urchin-cgm#17]
Hi,
great watchface! Just found it today and it will take me quite some time to figure out all possible settings. Fantastic work and all the possibilities to adopt layout to my preferences. Thanks for all the work you put in this!
I was looking for a possibility to add the date (i.e. June 18) below the current time. Is there a way to do this? Tx. 
Joe

**Comment by mddub** [comment]
Thanks! Showing the date is not supported right now, but it's a high priority on the roadmap. For now, you could show it in the status bar as part of a "custom URL" status (with the "multiple" status option if you want to show other status text above/below it).

**Comment by mddub** [comment]
http://www.timeapi.org/ lets you do this fairly easily, with support for a specific time zone and lots of formatting options:

For example, I would use this for PDT:
http://www.timeapi.org/pdt?format=%25a%20%25b%20%25d

**Comment by xJoe** [comment]
Thank you. I try using the URL you posted  (Custom URL Text) but it displays only -. If I copy the URL to safari the date is displayed. Can you give me a hint what I do wrong?

**Comment by mddub** [comment]
You're right: this ended up revealing an absurdly subtle bug. Short story is that it's fixed in the latest release, so if you reinstall the watchface, that URL should work now.

Long story is that Pebble has a slight inconsistency across platforms. The emulator doesn't decode the data returned by the config page in the same way as the iOS/Android apps, and Urchin was assuming the emulator's behavior reflected all platforms. As such, a URL like the one from timeapi.org (containing `%`) kind of breaks everything. I've submitted a [pull request](https://github.com/pebble/pebble-tool/pull/30) to fix the inconsistency in the Pebble emulator. Until then, I added a workaround to Urchin in https://github.com/mddub/urchin-cgm/commit/101532.

Either way, I'm suggesting you show the date via an extra web request only as a slightly crazy last resort until the watchface has real support for it. :)

**Comment by tuzoenduro** [comment]
I still get - as a date stamp even if I use the same link you used. I just installed the watchface this afternoon so I'm sure it is the latest one.

Is this because I'm installing through an iphone?

**Comment by tuzoenduro** [comment]
One question, how do we add a +2 to the timeapi setup?
I live in France, so GMT+2, but so far I can only put GMT otherwise I get errors.

Minor issue, as it only means that the new date will roll at 2am instead of midnight, but still...

Thanks!

**Comment by mddub** [comment]
@tuzoenduro see the http://www.timeapi.org/ docs. Chronic has a list of all the format options and time zones somewhere.

Or I believe you can do something like
http://www.timeapi.org/gmt/in-two-hours?format=%25a%20%25b%20%25d

**Comment by xJoe** [comment]
@tuzoenduro: I use now http://www.timeapi.org/cet?format=%25a%20%25b%20%25d
See https://www.timeanddate.com/time/zones/ for other time zone abbreviations

**Comment by mddub** [comment]
The current release, v0.0.13, adds a "Date" status bar option with configurable format.

If anyone is interested in non-English translations, please make changes to [status_formatters.js](https://github.com/mddub/urchin-cgm/blob/95eafda/src/js/status_formatters.js#L3-L11) and submit a pull request.
